on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: welcome message
        run: echo "my first GitHub Actions workflow,hwllo form ${{vars.NAME}} and my password is ${{secrets.PASSWRD}}"
      
      - name: list files
        run: ls
      
      - name: read file
        run: cat README.md
